# Terraform Provider testing workflow.
name: Tests

# This GitHub action runs your tests for each pull request and push.
# Optionally, you can turn it on using a schedule for regular testing.
on:
  pull_request:
    paths-ignore:
      - 'README.md'
    branches:
      - 'main'

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

# Default values to simplify job configurations below.
env:
  # Go language version to use for building. This value should also be updated
  # in the release workflow if changed.
  GO_VERSION: '1.19'

jobs:
  # Check Lint before building
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: v1.50.1

  # Ensure project builds before running testing matrix
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v3
      - run: go mod download
      - run: go build -v .

  # Run acceptance tests in a matrix with Terraform CLI versions
  test:
    name: Terraform Provider Acceptance Tests
    needs: [lint, build]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        # list whatever Terraform versions here you would like to support
        terraform:
          - '1.1.*'
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - uses: actions/checkout@v3
      - name: config rights
        run: >
          sudo chown 1000:1000 ${{ github.workspace }}/.github/provider/config.xml &&
          sudo chmod +x ${{ github.workspace }}/.github/provider/test.sh
      - name: run provider
        run: docker-compose -f ${{ github.workspace }}/.github/provider/docker-compose.yml up -d
      - run: go mod download
      - env:
          WHISPARR_URL: "http://localhost:6969"
          WHISPARR_API_KEY: "b01df9fca2e64e459d64a09888ce7451"
          TF_ACC: "1"
        run: go test -v -cover ./internal/provider/
        timeout-minutes: 10
